### ISSUE TITLE
You tried to plan twice at t/9reopenfh.t

### ISSUE THREAD

**Issue by eserte** [hoytech/Log-File-Rolling#1]
If Test::Fork is not installed, then t/9reopenfh.t fails:

```
perl5.23.9 -Mblib t/9reopenfh.t 
You tried to plan twice at t/9reopenfh.t line 9.
# Looks like your test exited with 2 before it could output anything.
```

Problem: the test specifies `no_plan` AND may do the `skip_all`. This does not work.  A fix may look like this:

```
diff --git a/t/9reopenfh.t b/t/9reopenfh.t
index 8dada97..597be3b 100644
--- a/t/9reopenfh.t
+++ b/t/9reopenfh.t
@@ -3,10 +3,11 @@

 #########################

-use Test::More qw/no_plan/;
+use Test::More;
 eval "
 use Test::Fork; ";
 plan skip_all => "Test::Fork required for this test" if $@;
+plan 'no_plan';

 use Log::File::Rolling;

```

**Comment by hoytech** [comment]
Thanks! I actually did exactly what you suggest a week or two ago, I just forgot to release it:

https://github.com/hoytech/Log-File-Rolling/commit/c489b1c35d5657c4ecc65c8e493a07bd4a7aea81

Releasing now.

Cheers,

Doug
